Saving framework log to /Users/emchandwani/psm-interop/out/run/20250408-112536-cloud_run_csm_inbound_test.log
+ [11:25:36 IST]	 exec python tests/cloud_run_csm_inbound_test.py --flagfile=/Users/emchandwani/psm-interop/config/local-dev.cfg
Running tests under Python 3.10.16: /Users/emchandwani/psm-interop/venv/bin/python
I0408 11:25:37.223489 8473956224 xds_k8s_testcase.py:177] ----- Testing CloudRunCsmInboundTest -----
I0408 11:25:37.223536 8473956224 xds_k8s_testcase.py:178] Logs timezone: IST
I0408 11:25:37.223610 8473956224 xds_k8s_testcase.py:106] Detected language and version: TestConfig(client_lang='cpp', server_lang='cpp', version=None)
I0408 11:25:39.002089 8473956224 k8s.py:264] Using kubernetes context "gke_emchandwani-default_us-central1-a_xds-k8s-interop-tests-cluster5", active host: https://34.55.128.246
W0408 11:26:54.009544 8473956224 connectionpool.py:823] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x108481120>, 'Connection to 34.55.128.246 timed out. (connect timeout=None)')': /version
Traceback (most recent call last):
  File "/Users/emchandwani/psm-interop/tests/cloud_run_csm_inbound_test.py", line 69, in <module>
    absltest.main(failfast=True)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/testing/absltest.py", line 2131, in main
    _run_in_app(run_tests, args, kwargs)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/testing/absltest.py", line 2236, in _run_in_app
    app.run(main=main_function)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/testing/absltest.py", line 2234, in main_function
    function(argv, args, kwargs)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/testing/absltest.py", line 2689, in run_tests
    result, fail_when_no_tests_ran = _run_and_get_tests_result(
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/testing/absltest.py", line 2653, in _run_and_get_tests_result
    test_program = unittest.TestProgram(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/absl/testing/_pretty_print_reporter.py", line 82, in run
    return super(TextTestRunner, self).run(test)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 114, in run
    self._handleClassSetUp(test, result)
  File "/opt/homebrew/Cellar/python@3.10/3.10.16/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/suite.py", line 166, in _handleClassSetUp
    setUpClass()
  File "/Users/emchandwani/psm-interop/framework/xds_k8s_testcase.py", line 1428, in setUpClass
    super().setUpClass()
  File "/Users/emchandwani/psm-interop/framework/xds_k8s_testcase.py", line 1082, in setUpClass
    super().setUpClass()
  File "/Users/emchandwani/psm-interop/framework/xds_k8s_testcase.py", line 247, in setUpClass
    cls.k8s_api_manager = k8s.KubernetesApiManager(
  File "/Users/emchandwani/psm-interop/framework/infrastructure/k8s.py", line 145, in __init__
    self._dynamic_client = dynamic.DynamicClient(self._client)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/dynamic/client.py", line 84, in __init__
    self.__discoverer = discoverer(self, cache_file)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/dynamic/discovery.py", line 228, in __init__
    Discoverer.__init__(self, client, cache_file)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/dynamic/discovery.py", line 54, in __init__
    self.__init_cache()
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/dynamic/discovery.py", line 70, in __init_cache
    self._load_server_info()
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/dynamic/discovery.py", line 145, in _load_server_info
    'kubernetes': self.client.request('get', '/version', serializer=just_json)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/dynamic/client.py", line 55, in inner
    resp = func(self, *args, **kwargs)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/dynamic/client.py", line 273, in request
    api_response = self.client.call_api(
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/client/rest.py", line 244, in GET
    return self.request("GET", url,
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/kubernetes/client/rest.py", line 217, in request
    r = self.pool_manager.request(method, url,
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/emchandwani/psm-interop/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt
